---
pagetitle: "R User Group Spatial Workshop 2019"
title: "R Spatial Workshop"
date: "Updated: `r format(Sys.Date())`"
---

### Workshop Description
This workshop will focus on the fundamentals of working with spatial data in R – reading and writing spatial data, dealing with map projections, packages for handling both vector and raster data, and visualizing and mapping spatial data in R. After covering fundamentals, we’ll move through example exercises demonstrating spatial operations such as spatial joins, spatial subsetting, spatial aggregation, cropping raster data, and extracting raster data for point. We’ll make use of packages such as `sf`, `sp`, `raster`, `rgdal`, `maptools`, and several others. A basic working knowledge of R will be assumed.

### Credits
Some content borrowed and modified from an [earlier workshop](https://mhweber.github.io/AWRA_GIS_R_Workshop/) I gave at the [2018 AWRA GIS Spring Specialty Conference](https://www.awra.org/meetings/Orlando2018/index.html), some of which was subsequently used as well by Ryan Hill and Marcus Beck for a [workshop they gave at the 2018 SFS conference](https://ryan-hill.github.io/sfs-r-gis-2018/).  Some material they developed for this workshop I've used and modified here as well with their permission.  

*Course pages created using RStudio, rmarkdown and knitr.*
